# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180409_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='../../media_cdn/dummy.png', height_field='height_field', upload_to=posts.models.upload_location, width_field='width_field'),
        ),
    ]
