# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180409_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mine',
            new_name='my_photo',
        ),
    ]
