# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180409_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
